FROM rust:1.42
RUN cargo install diesel_cli --no-default-features --features postgres

FROM rust:1.42-slim
RUN apt-get update -qq && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
COPY --from=0 /usr/local/cargo/bin/diesel /bin/diesel
RUN diesel --version
